version: '3'
services:
  bot:
    container_name: bot
    image: sedutorpretto/enduro_bot:latest
    restart: unless-stopped
    env_file: '.env'
    environment:
      REDIS_HOST: redis-fsm
      REDIS_PORT: 6379
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    depends_on:
      - redis-fsm
      - postgres

  redis-fsm:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: '.env'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  redis_data:
  postgres_data:
