version: '3'
services:
  bot:
    image: sedutorpretto/enduro_bot:latest
    restart: unless-stopped
    env_file: '.env'
    environment:
      REDIS_HOST: redis-fsm
      REDIS_PORT: 6379
    depends_on:
      - redis-fsm
      - postgres

  redis-fsm:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    env_file: '.env'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  redis_data:
  postgres_data: